---
- hosts: db_servers
  gather_facts: "{{ gather_y_n }}"
  become: true
  remote_user: "azureuser"
  vars_files:
   - ../secret/secret.yml
  roles:
   - common
   - base
   - DB_adm
   - restore
   - finals
