---
- hosts: webservers
  gather_facts: "{{ gather_y_n }}"
  become: true
  remote_user: "ubuntu"
  vars_files:
   - ../secret/secret.yml
  roles:
   - Restore

- hosts: mediawiki
  gather_facts: "{{ gather_y_n }}"
  become: true
  remote_user: "ubuntu"
  vars_files:
   - ../secret/secret.yml
  roles:
   - Restore
