---
- hosts: webservers
  gather_facts: "{{ gather_y_n }}"
  become: true
  remote_user: "ubuntu"
  vars_files:
   - ../secret/general.yml
   - ../secret/base.yml
   - ../secret/users.yml
   - ../secret/gitcfg.yml
   - ../secret/phpcfg.yml
   - ../secret/python.yml
   - ../secret/sslcrt.yml
   - ../secret/db_adm.yml
   - ../secret/drupal.yml
   - ../secret/finals.yml
   - ../secret/secret.yml
   - ../secret/remove.yml
  roles:
   - common
   - uninst
