---
- name: Set php.ini file ----------------------------------
  ini_file:
    path: "{{ php_ini_file }}"
    section: "{{ item.section }}"
    option: "{{ item.option }}"
    value: "{{ item.value }}"
  loop: "{{ php_ini_pairs }}"
  register: php_ini_updated
  tags: config_files, config_php_files, deploy_templates

- name: Remove undesired files (absent in item.types) -----
  file: 
    path: "{{ item.dest }}" 
    state: "absent"
  when: '"absent" in item.types'
  loop: "{{ all_descriptor_list }}"
  register: removed_files
  tags: config_files, deploy_templates

- name: Deploy templates all_descriptor_list.types=tmpl ---
  template: 
    src: "{{ item.name }}.j2" 
    dest: "{{ item.dest }}/{{ item.name }}"
  loop: "{{ all_descriptor_list }}"
  when: directories_in_place is success and "tmpl" in item.types
  register: templates_in_place
  tags: config_files, deploy_templates

- name: Make proper links all_descriptor_list.types=link --
  file: 
    src: "{{ item.src }}/{{ item.name }}" 
    dest: "{{ item.dest }}/{{ item.name }}" 
    state: link
  loop: "{{ all_descriptor_list }}"
  when: removed_files is success and templates_in_place is success and "link" in item.types
  register: links_in_place
  tags: config_files, deploy_templates

# Our server is SSL - check first certs
- name: Upload cert and key files if needed ---------------
  copy:
    dest: "{{ item.dest }}"
    src: "{{ item.src }}"
  loop: "{{ up_down_cert_files_list }}"
  register: cert_uploaded
  tags: config_files, ssl_certificate, key_cert_copy_only
  
# Can optionally stop or disable
- name: Ensure web service is restarted and enabled -------
  service: 
    name: "{{ web_service }}" 
    state: "restarted"
    enabled: true
  when: php_ini_updated is changed or removed_files is changed or templates_in_place is changed or links_in_place is changed or cert_uploaded is changed
  tags: install_dep_pkg,config_files, config_php_files, deploy_templates
