---
- name: Reboot RDS instance by name -------
  rds:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    command: reboot
    region: "{{ region }}"
    instance_name: "{{ db_instance_name }}"
  when: db_instance_name is defined and false
  tags: reboot_rds_instance, reboot_instance

# terminate (or absent) is in delete.yml task file
- name: Start/stop EC2 instances by tags --
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: "{{ item.state }}"
    region: "{{ region }}"
    instance_tags: "{{ item.tags }}"
    wait: "yes"
  loop: "{{ ec2_instances_by_tag }}"
  register: instances_state
  when: (ec2_instances_by_tag is defined and all_ec2_instances_state is not defined) and
        (item.state == "running" or item.state == "stopped" or item.state == "rebooted")
  tags: change_state_ec2_instance, change_state_instance

# when: check definition of 'instances_state' to avoid conflict
- name: Start/stop all EC2 instances ------
  ec2:
    aws_access_key: "{{ aws_access_key }}"
    aws_secret_key: "{{ aws_secret_key }}"
    state: "{{ all_ec2_instances_state }}"
    region: "{{ region }}"
    instance_ids: "{{ item.instance_id }}"
    wait: "yes"
  loop: "{{ ec2_facts.instances }}"
  when: all_ec2_instances_state is defined
  register: instances_state
  tags: change_state_all_ec2_instances, change_state_all_instances

