---
# Base example yml var file
#
# Our web server definitions
#
www_basedir             : "/var/www"
www_htmldir             : "{{ www_basedir }}/html"
www_username            : "www-data"
web_service             : "nginx"                                       # will be used more than once later
#
# Mediawiki source path (current version)
mediawiki_ver 		: "mediawiki-1.32.0"
# General package and service hash list
#
# If a packet has a service associate it should be listed with srv, state and enabled.
# enabled and state defaults to true and started respectively.
dep_pkg_list		:
   - { pkg : "{{ web_service }}" ,  srv : "{{ web_service }}" , state : "started" , enabled : true }
   - { pkg : "php"               ,  srv : "php7.0-fpm"        , state : "started" , enabled : true }
   - { pkg : "php-mysql"       }
   - { pkg : "php-gd"          }
   - { pkg : "php-json"        }
   - { pkg : "php-curl"        }
   - { pkg : "php-mbstring"    }
   - { pkg : "php-xml"         }
   - { pkg : "php-mcrypt"      }
   - { pkg : "php-apcu"        }
   - { pkg : "php7.0-intl"     }
   - { pkg : "mysql-client"    }
#   - { pkg : "composer"		}
#   - { pkg : "git"		}
#
# dir, file, template or link, depending on key values
#
# Will be used in template and file modules to create, delete and link.
#
# This dir_file_tmpl_list dict var will be used in 4 different tasks, one of 
# each type: tmpl, dir, link and file.
#
# If mode not present, it will default to 0644
# Note that one line may be used to multiple goals as defined in types.
# "dir" uses dest only
# "link" uses src and dest: ln -s src dest (force=yes => ln -s -f)
# "tmpl" uses name and dest: name.j2 -> dest/name
# "absent" uses dest to remove files
dir_file_tmpl_list     :
   - { types : [ "dir" , "tmpl" ] , dest : "/var/lib/mediawiki/{{ mediawiki_ver }}" , name : "LocalSettings.php" }
   - { types : [ "link" ]         , src  : "/var/lib/mediawiki/{{ mediawiki_ver }}" , dest : "/var/www/html/mediawiki" , force : "yes" }
   - { types : [ "dir" , "tmpl" ] , dest : "/etc/nginx/sites-available" , name : "nginx-default" }
   - { types : [ "link" ]         , src  : "/etc/nginx/sites-available/nginx-default" , dest : "/etc/nginx/sites-enabled/nginx-default" }
   - { types : [ "absent" ]       , dest : "/etc/nginx/sites-enabled/default" }
#   - { types : [ "tmpl" ]         , dest : "~ubuntu"                    , name : "updatedns.sh" , mode : "0755" }
#   - { types : [ "tmpl" ]         , dest : "/etc/nginx/snippets"        , name : "{{ domain2 }}-cert.conf"  , srv : "{{ web_service }}" }
#   - { types : [ "tmpl" ]         , dest : "/etc/nginx/sites-available" , name : "{{ domain2 }}.conf"       , srv : "{{ web_service }}" }
#   - { types : [ "link" ]         , src  : "/etc/nginx/sites-available/{{ domain2 }}.conf" , dest : "/etc/nginx/sites-enabled" }

#   - { types : [ "dir" , "tmpl" ] , dest : "/etc/nginx/sites-available" , name : "Drupal-site" }
#   - { types : [ "dir" , "tmpl" ] , dest : "/etc/nginx/snippets"        , name : "drupalcert.conf" }
#   - { types : [ "dir" , "link" ] , src  : "/etc/nginx/sites-available/Drupal-site" , dest : "/etc/nginx/sites-enabled" }

#
# INI file configuration (php and others)
#
ini_file_list           :
   - { path : "/etc/php/7.0/fpm/php.ini" , section : "PHP" , option : "memory_limit"    , value : "128M" }
#
# Cron
#
cron_list	:
   - false
#   - { name: "Update domain" , minute: "*/5" , job: "~ubuntu/updatedns.sh"  , user: "ubuntu" , state: "present" }

# Define local and remote files both for upload (copy)
# and download (fetch).
# Action is mandatory (same idea of types in dir_file_tmpl_list above).
# action = list of upload or download or both
up_down_files_list :
   - false
#   - { 
#        local  : "{{ confdir }}/drupal.key",
#        remote : "/etc/ssl/private/drupal.key" ,
#        action : [ "upload", "download" ]
#     }

# List of tar/zip balls to unarchive to specific places.
# Must define what it creates to be idempotent.
unarchive_list  :
   - {
        src         : "https://releases.wikimedia.org/mediawiki/1.32/mediawiki-1.32.0.tar.gz" ,
        dest        : "/var/lib/mediawiki" ,
        creates     : "/var/lib/mediawiki/{{ mediawiki_ver }}/index.php" ,
        owner       : "root" ,
        group       : "root" ,
        remote_src  : true
     }
