---
- name: Generate private key for account and csr ----------
  openssl_privatekey:
    path: "{{ item }}"
  loop:
    - "{{ cert_params_hash.account_private_key_path }}"
    - "{{ cert_params_hash.csr_private_key_path }}"
  when: cert_hash_list[0]
  register: private_key_created
  tags: ssl_certificate

- name: Create CSR certificate ----------------------------
  openssl_csr:
    path: "{{ item.site_csr_cert_path }}"
    privatekey_path: "{{ item.csr_private_key_path }}"
    C: "{{ item.C }}"
    ST: "{{ item.ST }}"
    L: "{{ item.L }}"
    O: "{{ item.O }}"
    OU: "{{ item.OU }}"
    E: "{{ item.email_address }}"
    CN: "{{ item.CN }}"
  loop: "{{ cert_hash_list }}"
  when: private_key_created is success
  register: csr_cert_created
  tags: ssl_certificate

- name: Create ACME account with respective email ---------
  acme_account:
    account_key_src: "{{ item.account_private_key_path }}"
    acme_version: '2'
    acme_directory: "{{ item.acme_directory }}"
    terms_agreed: yes
    state: present
    allow_creation: "{{ item.allow_creation_y_n }}"
    contact:
      - "mailto:{{ item.email_address }}"
  when: private_key_created is success
  register: acme_account_created
  tags: ssl_certificate

