---
# When keyUrl or repoStr are false (no quotes!) it bypasses in the task
listAptRepos :
   - {
        state   : "present" ,
        keyUrl  : "https://pkg.jenkins.io/debian-stable/jenkins.io.key" ,
        repoStr : "deb https://pkg.jenkins.io/debian-stable binary/"
     }
   - {
        state   : "present" ,
        keyUrl  : false ,
        repoStr : false
     }

dep_pkg_list            :
   - { pkg : "jenkins" }
#   - { pkg : "{{ web_service }}" ,  srv : "{{ web_service }}" , state : "started" , enabled : true }
#   - { pkg : "php"               ,  srv : "php7.0-fpm"        , state : "started" , enabled : true }
