---
listAptRepos :
   - {
        state   : "present" ,
        keyUrl  : "https://pkg.jenkins.io/debian-stable/jenkins.io.key" ,
        repoStr : "deb https://pkg.jenkins.io/debian-stable binary/"
     }
   - {
        state   : "false" ,
        keyUrl  : "false" ,
        repoStr : "deb https://pkg.jenkins.io/debian-stable binary/"
     }

dep_pkg_list            :
   - { pkg : "jenkins" }
#   - { pkg : "{{ web_service }}" ,  srv : "{{ web_service }}" , state : "started" , enabled : true }
#   - { pkg : "php"               ,  srv : "php7.0-fpm"        , state : "started" , enabled : true }
