---
update_cache_y_n:	false
# If you delete/terminate an instance and keep its name in the list below (unless 
# with state absent), the instances|sg|keys will be recriated in next call 
# to the playbook.
# id: is the idempotent factor and in our task is built using the formula below:
# "{{ region + '_' + item.tags.Name + '_' + item.type + '_' + item.image }}"
# Where item is one element from the ec2_instances_by_tag list defined here.
# states available: running, stopped, rebooted
ec2_instances_by_tag      : 
   - { 
       tags      : { Name : "server2" }, 
       state     : "running",
       SG_name   : "{{ srv_sg_name }}", 
       type      : "{{ srv_instance_type }}",
       image     : "ami-6b3fd60c",
       key_name  : "{{ linuxkey }}"
     }
#really_delete_rds         : true
#db_instance_name_to_delete: [ "dolibarrinstance" ]
db_sg_name                : "mysql"
rds_instances_by_name     :
   - { 
       tags      : { Environment: "testing",  Application: "Dolibarr" },
       type      : "db.t2.micro",
       name      : "websiteinstance",
       engine    : "mariadb",
       size      : "20",
       sg_name   : "{{ db_sg_name }}",
       username  : "admin",
       password  : "Admin1234"
     }

