---
- name: Drop databases --------------------
  mysql_db:
    login_user: "{{ item.admuser }}"
    login_password: "{{ item.admpass }}"
    login_host: "{{ item.host }}"
    name: "{{ item.dbname }}"
    state: absent
  loop: "{{ db_list }}"
  when: item.dbcreate
  register: databases_dropped
  tags: drop_databases

# Keep html empty
- name: Remove drupal site directory ------
  file:
    path: "{{ drupal_site_rootdir }}/"
    state: absent
  register: drupal_basedir_moved
  tags: remove_drupal_installation

- name: Uninstall Drupal dependencies -----
  apt: 
    pkg: "{{ item.pkg }}" 
    state: "absent"
    purge: "{{ purge_y_n }}" 
    autoremove: "{{ autoremove_y_n }}"
  loop: "{{ dep_pkg_list }}"
  register: drupal_dep_pkg_uninstalled
  tags: uninstall_dep_pkg

# Remove other parts (check condition below)
- name: Remove other files or directories -
  file: 
    path: "{{ item }}"
    state: absent
  loop: "{{ remove_list }}"
  when: purge_y_n and autoremove_y_n and drupal_dep_pkg_uninstalled is success
  register: drupal_basedir_moved
  tags: uninstall_dep_pkg, remove_drupal_installation

